Feature/login
mash-up-kr/Tich-Android pull request #11
Opened 2020-10-09 10:50 UTC by d2fault

## 반영 내용

- Google Sign-up & Sign-in 기능
- '구글아이디로 시작하기' 버튼 클릭시 token이 있다면 sign-in, 없다면 sign-up으로 동작
  - 앱 삭제후 reinstall시 꼭! `WalkLastFragment` 의 `onViewCreated` 로직에서 서버에서 발급받은 token을 임의로 save하여 사용할 것(`authManager.saveToken("자신의 토큰")`)
  - 다른 방법으로 swagger에서 '탈퇴하기' 후 재가입이 있으나 현재 탈퇴하기 기능 정상 동작 X

<br>

2020-10-09 10:56 UTC, mkSpace requested changes

2020-10-09 10:56 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/data/repository/AuthRepository.kt
> +        remote.signIn()
이거 올려주세요,.

fun signIn(): ~ = remote.signIn()

2020-10-09 10:56 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +            if (authManager.getToken().isNullOrBlank()) {
여기에 해당하는 로직은 ViewModel로 빠져야 합니다

2020-10-09 10:56 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/viewmodel/WalkLastViewModel.kt
> +    private val TAG = "WalkLastViewModel"
companion object에 넣어주세요

2020-10-09 10:56 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/viewmodel/WalkLastViewModel.kt
> +            .doOnSuccess { authManager.saveToken(it.token) }
signIn에서도 token을 저장하나요?

2020-10-09 10:56 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/viewmodel/WalkLastViewModel.kt
> +        authRepository.signUp(token, name, email)
.subscribeWithErrorLogger 만들어 둔게 있습니다. 에러 발생 시 Error Log를 찍어주기 위해 만들었으니 이걸 사용해주세요

2020-10-09 10:56 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/viewmodel/WalkLastViewModel.kt
> +            .subscribe()
Disposable를 생성하면 생성된 disposable들을 CompositeDisposable에 넣어야합니다.
.addToDisposables() 넣어주세요

2020-10-09 18:28 UTC, mkSpace requested changes

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/data/model/UserInfo.kt
> +    val id: Int,
이거 개행해서 쓰지 말고 붙여서 써주세요. 
@SerializedName("id") val id: Int

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/data/remote/AuthRemoteDataSource.kt
> +    ): Single<UserInfo> = service.signUp(requestBodyOf {
token만 필요한거면 .map {} 을 통해서 반환형을 String으로 바꿔주세요

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/data/remote/AuthRemoteDataSource.kt
> +    fun signUp(
여기 파라미터들 한 줄로 배치해주세요.

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
>  class WalkLastFragment : Fragment() {
BaseViewModelFragment 사용해주세요

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
>      override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
onSetUpViews override해서 넣어주세요

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +                viewModel.signIn()
우리는 로그인 하고 -> startTich를 해줘야 하기떄문에 signIn을 Completable로 만들어주고 subscribe의 결과로 startTich 해주세요. 이러면 로그인도 안된채 startTich가 될 수 있습니다.

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +                    startTich()
여기도 위와 동일합니다 . signUp을 Completable로 변경해주세요

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +        activity?.finish()
requireActivity()를 호출해서 activity를 갖고 올 수 있습니다.

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +        startActivity(intent)
이건 한 줄로 만들수 있을거 같아요

2020-10-09 18:28 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/viewmodel/WalkLastViewModel.kt
> +        token: String,
여기도 파라미터 한 줄로 배치해주세요

2020-10-10 03:09 UTC, d2fault commented on app/src/main/java/com/example/tichandroid/viewmodel/WalkLastViewModel.kt
> +            .doOnSuccess { authManager.saveToken(it.token) }
signIn에서도 token을 보내주기에 갱신하는 느낌으로 저장 로직 포함했습니다!

2020-10-10 05:06 UTC, merged