Feature/modify item add
mash-up-kr/Tich-Android pull request #14
Opened 2020-10-21 07:28 UTC by SeungYooon

2020-10-24 16:53 UTC, mkSpace requested changes

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/MainActivity.kt
> +                0 -> loadFragment(ItemFragment(R.layout.fragment_shaving))
Fragment에 constructor를 만드는 방식은 좋지 않아요. Fragment는 기본 생성자를 생성해서 생성해야 합니다.
Fragment 생성 시에 특정 변수를 활용하기 위해선 ItemFragment 내에 newInstance와 같은 companion object에 static function을 넣어주어서 처리하는 방식이나 Bundle을 통해 parameter를 전달해야 합니다.

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/CycleDialogFragment.kt
> +                txtAboveThumb.text = value.toString().plus("일")
위와 같이 바꿔주세요.

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/CycleDialogFragment.kt
> +                txtAboveThumb.text = value.toString().plus("주")
이것도 위와같이 바꿔주세요.

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/CycleDialogFragment.kt
>          seekBar.setOnSeekBarChangeListener(object : SeekBar.OnSeekBarChangeListener {
리스너를 왜 every week 가 클릭 될때 세팅해주나요? setUpViews로 옮겨주세요

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/CycleDialogFragment.kt
>          seekBar.setOnSeekBarChangeListener(object : SeekBar.OnSeekBarChangeListener {
이것도 마찬가지로여

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/CycleDialogFragment.kt
> +                txtAboveThumb.text = value.toString().plus("달")
여기두

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/items/ItemFragment.kt
> +class ItemFragment(private val layoutId: Int) : BaseViewModelFragment() {
이거 생성자 지워주시고. 위에 제가 리뷰한대로 바꿔주세요

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/items/ItemFragment.kt
> -        return inflater.inflate(R.layout.fragment_shaving, container, false)
이거 제가 extension 만들어 두긴 했는뎅..

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/items/ItemFragment.kt
> +    override fun onBindViewModels() {
onBindViewModels는 viewModel를 구독하는 function을 모아놓는 곳이에요.
아래와 같이 클릭 리스너 콜백에 해당하는 경우는 setUpViews에서 처리해주세요.

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/items/ItemFragment.kt
> +                Handler().postDelayed(::originBtn, 1000)
이렇게 구현하는건 좋지않아요.
UI를 비동기 식으로 그것도 타이머의 형식으로 핸들링해주는건 좋지 않은 방식이에요.
꼭 클릭 된 후 1초를 기다려야 하는 이유가 있나요?

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/viewmodel/ShavingViewModel.kt
> +    private val isEmptyProcessor = BehaviorProcessor.createDefault(false)
여기는 isEmptyProcessor는 없어도 될 것 같아요

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/res/layout/activity_main.xml
>          android:id="@+id/img_name"
여기 camel 이에요

2020-10-24 16:53 UTC, mkSpace commented on app/src/main/res/layout/fragment_dish_cloth.xml
> -<?xml version="1.0" encoding="utf-8"?>
여기 xml 파일들도 하나로 묶어주세요

2020-10-24 17:00 UTC, mkSpace commented
그리고 바텀시트쪽 제가 layout쪽을 제대로 안봐서 그런데 현재 바텀 시트 띄우면 좀 이상하게 삐뚤삐뚤하게 나오는데 이거 확인되시나요??

2020-10-26 13:42 UTC, SeungYooon commented
> 그리고 바텀시트쪽 제가 layout쪽을 제대로 안봐서 그런데 현재 바텀 시트 띄우면 좀 이상하게 삐뚤삐뚤하게 나오는데 이거 확인되시나요??

font 적용 후에 xml에서 삐뚤하게 나오는데,  실행했을때 맞도록 바꿔놓긴 했어.
앱 실행해서 한번 삐뚤한지 확인해봐

2020-10-26 13:46 UTC, SeungYooon commented on app/src/main/java/com/example/tichandroid/view/ui/items/ItemFragment.kt
> +                Handler().postDelayed(::originBtn, 1000)
저 버튼을 클릭시에 버튼 색이 바뀌고 화면이 넘어가는 효과로는 저게 가장 자연스러워
Handler().post {}로 적용하게되면 너무 빠르게 버튼 색이 바꼈다 돌아와서 부자연스러워

2020-10-27 07:58 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/items/ItemFragment.kt
> +                Handler().postDelayed(::originBtn, 1000)
View.anite() 사용해 보시겠어요?

2020-11-01 03:51 UTC, merged