Feature/walkthrough
mash-up-kr/Tich-Android pull request #3
Opened 2020-10-02 13:04 UTC by d2fault

### 작업 내용

- google 로그인 연동 작업
- 로그인 관련 정보 수신까지 확인(이후 로직 추가 개발 필요)

<br>

### 테스팅 방법

- `google-services.json` 파일 추가
  - 경로: `/Tich-Android/app/`
- 테스팅 불가능할 경우 SHA1 key Firebase 콘솔에서 추가해야 함
  - Firebase id/password 및 SHA1 확인/추가 방법은 notion 참고

2020-10-02 14:28 UTC, d2fault commented
### 작업 내용

- 로그인 관련 정보 수신까지 확인(이후 로직 추가 개발 필요)

2020-10-02 14:30 UTC, SeungYooon reviewed
이미 구글 로그인을 했는지 확인하는 코드도 필요할듯해요. 
로그인 되어있다면 바로 main으로 넘어가는식으로

2020-10-02 14:30 UTC, SeungYooon commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +                Log.d(TAG, "firebaseAuthWithGoogle email: " + account.email)
Log는 지금 확인용으로 사용하고 최종에는 지우는 것을 추천합니다.

2020-10-02 14:30 UTC, SeungYooon commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
onActivityResult가 deprecated되었는데 새로운 API로 고쳐보는 것도 좋을듯합니다.

2020-10-04 10:30 UTC, merged

2020-10-04 10:34 UTC, mkSpace requested changes

2020-10-04 10:34 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +        val buttonGoogleLogin: com.shobhitpuri.custombuttons.GoogleSignInButton =
이거 com.~~~ 이거 다 지워주세요
import 제대로 하면 지워집니다!

2020-10-04 10:34 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +            view.findViewById(R.id.google_login)
그리고 우리 기본적으로 ktx 방식으로 view 참조하기로 해서 google_login.~~ 그대로 사용하면돼!
layout 안에 있는 view id 는 camel case로 바꿔줘!

2020-10-04 10:34 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +                firebaseAuthWithGoogle(account.idToken!!)
account.idToken?.let { firebaseAuthWithGoogle(it) } 이걸로 바꿔주세요

2020-10-04 10:34 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +        startActivityForResult(signInIntent, RC_SIGN_IN)
Fragment에서 signIn 이런 표현방식보단 onHandleSignIn 내지 onSignInButtonClick 이걸로 바꾸면 좋을 것 같아요.
이벤트 콜백에 대한 처리의 의미가 더 부각되어야 한다고 생각합니다.

2020-10-04 10:34 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +                val account = task.getResult(ApiException::class.java)!!
여기 !! 지워주세요

2020-10-04 10:34 UTC, mkSpace commented on app/src/main/java/com/example/tichandroid/view/ui/WalkLastFragment.kt
> +                    Log.d(TAG, "signInWithCredential:success")
여기 로그 지워주세요.
develop 브랜치에 머지되야 하는 경우 에러나 워닝에 대한 로그가 아니면 전부 지워주세요!
만약 debug 빌드에서 로그를 띄워야 하는 상태이면 BuildConfig에서 BuildType 체크해서 로그를 띄워주는 방식으로 처리해야 해요